# Generated by Django 5.2 on 2025-04-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category_tb',
        ),
    ]
